version: '3'

networks:
  project-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.2.0/24
        gateway: 172.18.2.1

services:

  weather_frontend:
    image: nginx:latest
    restart: always
    hostname: weather_frontend
    container_name: weather_frontend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/dist:/opt/dist
    networks:
      project-net:
        ipv4_address: "172.18.2.22"
    environment:
      LANG: en_US.UTF-8
    ports:
      - 80:80
      - 443:443

  weather_backend:
    image: weather_backend:0.1-3.9.18
    restart: always
    hostname: weather_backend
    container_name: weather_backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      project-net:
        ipv4_address: "172.18.2.20"
    environment:
      LANG: en_US.UTF-8
    ports:
      - 8080:8080